Put an empty ^$ after wblank
I thought we were good because

```sh
$ echo '^ikkje<adv>/ikkje$ «[[tf:i:a]]s\^å[[/]]»' |cg-proc -1ng nob-nno.genprefs.rlx.bin
ikkje «[[tf:i:a]]s\^å[[/]]»
```

worked, but

If there's an analysis after the unmerged word blank, cg-proc errors out:

```sh
$ echo '^ikkje<adv>/ikkje$ «[[tf:i:a]]s\^å» ^.<sent>/.$' |cg-proc -1ng nob-nno.genprefs.rlx.bin
Error: Word-bound blank was not immediately prior to token on line 0
```

Fair enough, so lt-merge must put an empty ^$ after word blanks to
appease cg-proc. Seems like tf-inject finds the right point at which
to end it anyway?